/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/app/AppShell.vue')['default']
    BackupManager: typeof import('./src/components/app/BackupManager.vue')['default']
    CloneProgressDialog: typeof import('./src/components/dialog/CloneProgressDialog.vue')['default']
    CodexMainSession: typeof import('./src/components/app/CodexMainSession.vue')['default']
    ConfirmDialog: typeof import('./src/components/dialog/ConfirmDialog.vue')['default']
    CustomSelect: typeof import('./src/components/common/CustomSelect.vue')['default']
    FocusTerminalStack: typeof import('./src/components/terminal/FocusTerminalStack.vue')['default']
    OperationDialog: typeof import('./src/components/dialog/OperationDialog.vue')['default']
    ProjectAiSessions: typeof import('./src/components/git/ProjectAiSessions.vue')['default']
    ProjectCommitHistory: typeof import('./src/components/git/ProjectCommitHistory.vue')['default']
    ProjectDetail: typeof import('./src/components/git/ProjectDetail.vue')['default']
    ProjectPipeline: typeof import('./src/components/git/ProjectPipeline.vue')['default']
    ProjectSettingsDialog: typeof import('./src/components/dialog/ProjectSettingsDialog.vue')['default']
    ProjectSidebar: typeof import('./src/components/project-sidebar/ProjectSidebar.vue')['default']
    ProjectStashList: typeof import('./src/components/git/ProjectStashList.vue')['default']
    ProjectWorkspace: typeof import('./src/components/git/ProjectWorkspace.vue')['default']
    ProjectWorkspaceHost: typeof import('./src/components/app/ProjectWorkspaceHost.vue')['default']
    RemoteRepo: typeof import('./src/components/git/RemoteRepo.vue')['default']
    StandaloneSplitTerminal: typeof import('./src/components/terminal/StandaloneSplitTerminal.vue')['default']
    StandaloneTerminal: typeof import('./src/components/terminal/StandaloneTerminal.vue')['default']
    TerminalPanel: typeof import('./src/components/terminal/TerminalPanel.vue')['default']
    TerminalSplitNode: typeof import('./src/components/terminal/TerminalSplitNode.vue')['default']
    ThemePanel: typeof import('./src/components/app/ThemePanel.vue')['default']
    WorkspaceTextEditor: typeof import('./src/components/git/WorkspaceTextEditor.vue')['default']
  }
}
