/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/app/AppShell.vue')['default']
    BackupManager: typeof import('./src/components/BackupManager.vue')['default']
    Browser: typeof import('./src/components/browser/Browser.vue')['default']
    CloneProgressDialog: typeof import('./src/components/dialog/CloneProgressDialog.vue')['default']
    ConfirmDialog: typeof import('./src/components/dialog/ConfirmDialog.vue')['default']
    CustomSelect: typeof import('./src/components/common/CustomSelect.vue')['default']
    DownloadPanel: typeof import('./src/components/browser/DownloadPanel.vue')['default']
    ExtensionManager: typeof import('./src/components/ExtensionManager.vue')['default']
    FavoritesManager: typeof import('./src/components/browser/FavoritesManager.vue')['default']
    GitProject: typeof import('./src/components/git/GitProject.vue')['default']
    HistoryManager: typeof import('./src/components/browser/HistoryManager.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    NewTabPage: typeof import('./src/components/browser/NewTabPage.vue')['default']
    OperationDialog: typeof import('./src/components/dialog/OperationDialog.vue')['default']
    PasswordManager: typeof import('./src/components/browser/PasswordManager.vue')['default']
    PasswordSaveDialog: typeof import('./src/components/dialog/PasswordSaveDialog.vue')['default']
    ProjectAiSessions: typeof import('./src/components/git/ProjectAiSessions.vue')['default']
    ProjectBuildConfig: typeof import('./src/components/git/ProjectBuildConfig.vue')['default']
    ProjectCommitHistory: typeof import('./src/components/git/ProjectCommitHistory.vue')['default']
    ProjectDetail: typeof import('./src/components/git/ProjectDetail.vue')['default']
    ProjectFileStatus: typeof import('./src/components/git/ProjectFileStatus.vue')['default']
    ProjectManager: typeof import('./src/components/git/ProjectManager.vue')['default']
    ProjectPipeline: typeof import('./src/components/git/ProjectPipeline.vue')['default']
    ProjectSettingsDialog: typeof import('./src/components/dialog/ProjectSettingsDialog.vue')['default']
    ProjectSidebar: typeof import('./src/components/project-sidebar/ProjectSidebar.vue')['default']
    ProjectStashList: typeof import('./src/components/git/ProjectStashList.vue')['default']
    ProjectWorkspace: typeof import('./src/components/git/ProjectWorkspace.vue')['default']
    RemoteRepo: typeof import('./src/components/git/RemoteRepo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SitePermissionPanel: typeof import('./src/components/browser/SitePermissionPanel.vue')['default']
    StandaloneTerminal: typeof import('./src/components/terminal/StandaloneTerminal.vue')['default']
    TabManager: typeof import('./src/components/browser/TabManager.vue')['default']
    TerminalPanel: typeof import('./src/components/terminal/TerminalPanel.vue')['default']
    TerminalSplitNode: typeof import('./src/components/terminal/TerminalSplitNode.vue')['default']
    WebView: typeof import('./src/components/webview/WebView.vue')['default']
  }
}
