const { app, BrowserWindow, Menu, shell, dialog, ipcMain, session, protocol, net, screen } = require('electron')
const path = require('path')
const { exec, spawn, execFileSync } = require('child_process')
const { promisify, format } = require('util')
const fs = require('fs')
const https = require('https')
const http = require('http')
const { URL, pathToFileURL, fileURLToPath } = require('url')
const os = require('os')
const Store = (require('electron-store')).default || require('electron-store')
const pty = require('node-pty')
const { registerRefreshHandlers } = require('./ipc/refresh')
const { registerTerminalHandlers } = require('./ipc/terminal')
const { registerConfigHandlers } = require('./ipc/config')
const { registerFilesystemHandlers } = require('./ipc/filesystem')
const { registerAiSessionHandlers } = require('./ipc/ai-sessions')
const { registerBrowserDataHandlers } = require('./ipc/browser-data')
const { registerCommandHandlers } = require('./ipc/command')
const { registerNavigationHandlers } = require('./ipc/navigation')
const { registerProjectHandlers } = require('./ipc/projects')
const { registerWindowUiHandlers } = require('./ipc/window-ui')
const { registerBranchHandlers } = require('./ipc/branch')
const { registerExtensionHandlers } = require('./ipc/extensions')
const { registerScmHandlers } = require('./ipc/scm')
const { WebTabManager } = require('./tab-manager/web-tab-manager')
const { createSessionPartitionManager } = require('./tab-manager/session-partition-manager')
const { decideWindowOpenAction } = require('./tab-manager/window-open-policy')
const { createSitePermissionManager } = require('./permissions/site-permission-manager')

// 注册自定义协议（必须在 app ready 之前调用）
// local-resource:// 用于安全地向渲染进程提供 ~/.gitManager/ 目录下的本地文件
protocol.registerSchemesAsPrivileged([
  { scheme: 'local-resource', privileges: { secure: true, standard: true, supportFetchAPI: true, bypassCSP: false } }
])

const execAsync = promisify(exec)

async function executeCommandArgs(command, args = [], cwd, timeoutMs = 120000) {
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      cwd,
      stdio: ['ignore', 'pipe', 'pipe']
    })

    let stdout = ''
    let stderr = ''
    let settled = false

    const timeout = setTimeout(() => {
      if (settled) return
      settled = true
      child.kill('SIGTERM')
      setTimeout(() => {
        try { child.kill('SIGKILL') } catch (e) { /* ignore */ }
      }, 3000)
      resolve({
        success: false,
        error: `命令执行超时 (${timeoutMs / 1000}秒)`,
        stdout,
        stderr
      })
    }, timeoutMs)

    child.stdout.on('data', chunk => {
      stdout += chunk.toString()
    })

    child.stderr.on('data', chunk => {
      stderr += chunk.toString()
    })

    child.on('close', (code) => {
      if (settled) return
      settled = true
      clearTimeout(timeout)
      resolve({
        success: code === 0,
        error: code === 0 ? '' : `进程退出码: ${code}`,
        stdout,
        stderr
      })
    })

    child.on('error', (error) => {
      if (settled) return
      settled = true
      clearTimeout(timeout)
      resolve({
        success: false,
        error: error.message,
        stdout,
        stderr
      })
    })
  })
}

function writeFileIfChanged(filePath, content) {
  try {
    if (fs.existsSync(filePath)) {
      const current = fs.readFileSync(filePath, 'utf8')
      if (current === content) return
    }
    fs.writeFileSync(filePath, content, 'utf8')
  } catch (error) {
    safeError('❌ 写入终端启动脚本失败:', filePath, error.message)
  }
}

function ensureTerminalBootstrapFiles() {
  const bootstrapRoot = path.join(app.getPath('userData'), 'terminal-bootstrap')
  const zshDir = path.join(bootstrapRoot, 'zsh')
  const bashDir = path.join(bootstrapRoot, 'bash')

  fs.mkdirSync(zshDir, { recursive: true })
  fs.mkdirSync(bashDir, { recursive: true })

  const zshRcPath = path.join(zshDir, '.zshrc')
  const bashRcPath = path.join(bashDir, '.bashrc')

  writeFileIfChanged(zshRcPath, `# Auto-generated by OpenGit
if [ -n "$GIT_MANAGER_REAL_ZDOTDIR" ] && [ "$ZDOTDIR" != "$GIT_MANAGER_REAL_ZDOTDIR" ]; then
  export ZDOTDIR="$GIT_MANAGER_REAL_ZDOTDIR"
fi

if [ -n "$ZDOTDIR" ] && [ -f "$ZDOTDIR/.zshrc" ]; then
  source "$ZDOTDIR/.zshrc"
elif [ -f "$HOME/.zshrc" ]; then
  source "$HOME/.zshrc"
fi

_gitmanager_apply_cwd() {
  if [ -n "$GIT_MANAGER_INITIAL_CWD" ] && [ -d "$GIT_MANAGER_INITIAL_CWD" ] && [ "$PWD" != "$GIT_MANAGER_INITIAL_CWD" ]; then
    builtin cd -- "$GIT_MANAGER_INITIAL_CWD" 2>/dev/null || cd -- "$GIT_MANAGER_INITIAL_CWD"
  fi
}

_gitmanager_apply_cwd
`)

  writeFileIfChanged(bashRcPath, `# Auto-generated by OpenGit
if [ -n "$GIT_MANAGER_REAL_BASHRC" ] && [ -f "$GIT_MANAGER_REAL_BASHRC" ]; then
  . "$GIT_MANAGER_REAL_BASHRC"
elif [ -f "$HOME/.bashrc" ]; then
  . "$HOME/.bashrc"
fi

__gitmanager_apply_cwd() {
  if [ -n "$GIT_MANAGER_INITIAL_CWD" ] && [ -d "$GIT_MANAGER_INITIAL_CWD" ] && [ "$PWD" != "$GIT_MANAGER_INITIAL_CWD" ]; then
    builtin cd -- "$GIT_MANAGER_INITIAL_CWD" 2>/dev/null || cd -- "$GIT_MANAGER_INITIAL_CWD"
  fi
}

__gitmanager_apply_cwd
`)

  return { zshDir, bashRcPath }
}

function quoteShellArg(value) {
  return "'" + String(value).replace(/'/g, "'\\''") + "'"
}

function ensurePathEntries(pathValue, requiredEntries) {
  const delimiter = path.delimiter
  const currentParts = (pathValue || '')
    .split(delimiter)
    .map((part) => part.trim())
    .filter(Boolean)
  const existing = new Set(currentParts)
  const missing = requiredEntries.filter((entry) => !existing.has(entry))
  return [...currentParts, ...missing].join(delimiter)
}

let cachedSystemProxyEnv = null
let cachedSystemProxyEnvAt = 0
const SYSTEM_PROXY_ENV_TTL = 15 * 1000

function parseScutilProxyOutput(rawOutput = '') {
  const values = {}
  rawOutput
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .forEach((line) => {
      const match = line.match(/^([A-Za-z0-9]+)\s*:\s*(.+)$/)
      if (!match) return
      values[match[1]] = match[2]
    })
  return values
}

function buildProxyUrl({ scheme = 'http', host = '', port = '', username = '', password = '' } = {}) {
  if (!host || !port) return ''
  const auth = username
    ? `${encodeURIComponent(username)}${password ? `:${encodeURIComponent(password)}` : ''}@`
    : ''
  return `${scheme}://${auth}${host}:${port}`
}

function normalizeQuotedValue(value = '') {
  return String(value || '').trim().replace(/^'+|'+$/g, '').replace(/^"+|"+$/g, '')
}

function normalizeNoProxyList(values = []) {
  const out = []
  for (const raw of values) {
    const value = String(raw || '').trim()
    if (!value) continue
    if (value === '<local>') {
      out.push('localhost', '127.0.0.1')
      continue
    }
    out.push(value)
  }
  return [...new Set(out)].join(',')
}

function getMacSystemProxyEnv() {
  if (process.platform !== 'darwin') {
    return {}
  }

  const now = Date.now()
  if (cachedSystemProxyEnv && (now - cachedSystemProxyEnvAt) < SYSTEM_PROXY_ENV_TTL) {
    return { ...cachedSystemProxyEnv }
  }

  try {
    const output = execFileSync('scutil', ['--proxy'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    })
    const proxyConfig = parseScutilProxyOutput(output)
    const env = {}

    const httpProxy = Number(proxyConfig.HTTPEnable) === 1
      ? buildProxyUrl({
        scheme: 'http',
        host: proxyConfig.HTTPProxy,
        port: proxyConfig.HTTPPort,
        username: proxyConfig.HTTPUser,
        password: proxyConfig.HTTPPassword
      })
      : ''

    const httpsProxy = Number(proxyConfig.HTTPSEnable) === 1
      ? buildProxyUrl({
        scheme: 'http',
        host: proxyConfig.HTTPSProxy,
        port: proxyConfig.HTTPSPort,
        username: proxyConfig.HTTPSUser,
        password: proxyConfig.HTTPSPassword
      })
      : ''

    const socksProxy = Number(proxyConfig.SOCKSEnable) === 1
      ? buildProxyUrl({
        scheme: 'socks5',
        host: proxyConfig.SOCKSProxy,
        port: proxyConfig.SOCKSPort
      })
      : ''

    const noProxy = typeof proxyConfig.ExceptionsList === 'string'
      ? proxyConfig.ExceptionsList.replace(/[()"]/g, '').split(/\s*,\s*|\s+/).filter(Boolean).join(',')
      : ''

    if (httpProxy) {
      env.http_proxy = httpProxy
      env.HTTP_PROXY = httpProxy
    }

    if (httpsProxy || httpProxy) {
      const resolvedHttpsProxy = httpsProxy || httpProxy
      env.https_proxy = resolvedHttpsProxy
      env.HTTPS_PROXY = resolvedHttpsProxy
    }

    if (socksProxy) {
      env.all_proxy = socksProxy
      env.ALL_PROXY = socksProxy
    }

    if (noProxy) {
      env.no_proxy = noProxy
      env.NO_PROXY = noProxy
    }

    cachedSystemProxyEnv = env
    cachedSystemProxyEnvAt = now
    return { ...env }
  } catch (error) {
    cachedSystemProxyEnv = {}
    cachedSystemProxyEnvAt = now
    return {}
  }
}

function parseWindowsProxyServer(rawValue = '') {
  const text = String(rawValue || '').trim()
  if (!text) return {}

  const assignments = text.includes('=')
    ? text.split(';').map((item) => item.trim()).filter(Boolean)
    : [`http=${text}`, `https=${text}`]

  let httpProxy = ''
  let httpsProxy = ''
  let allProxy = ''

  for (const item of assignments) {
    const [rawKey, rawTarget] = item.includes('=') ? item.split('=') : ['http', item]
    const key = String(rawKey || '').trim().toLowerCase()
    const target = String(rawTarget || '').trim()
    if (!target) continue

    const buildPlainProxy = (scheme) => {
      try {
        const parsed = new URL(target)
        return buildProxyUrl({
          scheme,
          host: parsed.hostname,
          port: parsed.port || (scheme === 'http' ? '80' : ''),
          username: decodeURIComponent(parsed.username || ''),
          password: decodeURIComponent(parsed.password || '')
        })
      } catch {
        const [host, port] = target.split(':')
        return buildProxyUrl({ scheme, host, port })
      }
    }

    if (key === 'http') httpProxy = buildPlainProxy('http')
    else if (key === 'https') httpsProxy = buildPlainProxy('http')
    else if (key === 'socks') allProxy = buildPlainProxy('socks5')
  }

  return { httpProxy, httpsProxy, allProxy }
}

function getWindowsSystemProxyEnv() {
  if (process.platform !== 'win32') {
    return {}
  }

  const now = Date.now()
  if (cachedSystemProxyEnv && (now - cachedSystemProxyEnvAt) < SYSTEM_PROXY_ENV_TTL) {
    return { ...cachedSystemProxyEnv }
  }

  try {
    const output = execFileSync('reg', ['query', 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    })
    const values = {}
    output
      .split('\n')
      .map((line) => line.trim())
      .filter(Boolean)
      .forEach((line) => {
        const match = line.match(/^([A-Za-z0-9_]+)\s+REG_[A-Z0-9_]+\s+(.+)$/)
        if (!match) return
        values[match[1]] = String(match[2] || '').trim()
      })

    if (Number(values.ProxyEnable) !== 1) {
      cachedSystemProxyEnv = {}
      cachedSystemProxyEnvAt = now
      return {}
    }

    const { httpProxy, httpsProxy, allProxy } = parseWindowsProxyServer(values.ProxyServer)
    const noProxy = normalizeNoProxyList(String(values.ProxyOverride || '').split(';'))
    const env = {}

    if (httpProxy) {
      env.http_proxy = httpProxy
      env.HTTP_PROXY = httpProxy
    }
    if (httpsProxy || httpProxy) {
      const resolvedHttpsProxy = httpsProxy || httpProxy
      env.https_proxy = resolvedHttpsProxy
      env.HTTPS_PROXY = resolvedHttpsProxy
    }
    if (allProxy) {
      env.all_proxy = allProxy
      env.ALL_PROXY = allProxy
    }
    if (noProxy) {
      env.no_proxy = noProxy
      env.NO_PROXY = noProxy
    }

    cachedSystemProxyEnv = env
    cachedSystemProxyEnvAt = now
    return { ...env }
  } catch (error) {
    cachedSystemProxyEnv = {}
    cachedSystemProxyEnvAt = now
    return {}
  }
}

function getLinuxSystemProxyEnv() {
  if (process.platform !== 'linux') {
    return {}
  }

  const now = Date.now()
  if (cachedSystemProxyEnv && (now - cachedSystemProxyEnvAt) < SYSTEM_PROXY_ENV_TTL) {
    return { ...cachedSystemProxyEnv }
  }

  try {
    const execGsettings = (schema, key) => execFileSync('gsettings', ['get', schema, key], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim()

    const mode = normalizeQuotedValue(execGsettings('org.gnome.system.proxy', 'mode'))
    if (mode !== 'manual') {
      cachedSystemProxyEnv = {}
      cachedSystemProxyEnvAt = now
      return {}
    }

    const httpHost = normalizeQuotedValue(execGsettings('org.gnome.system.proxy.http', 'host'))
    const httpPort = normalizeQuotedValue(execGsettings('org.gnome.system.proxy.http', 'port'))
    const httpsHost = normalizeQuotedValue(execGsettings('org.gnome.system.proxy.https', 'host'))
    const httpsPort = normalizeQuotedValue(execGsettings('org.gnome.system.proxy.https', 'port'))
    const socksHost = normalizeQuotedValue(execGsettings('org.gnome.system.proxy.socks', 'host'))
    const socksPort = normalizeQuotedValue(execGsettings('org.gnome.system.proxy.socks', 'port'))
    const ignoreHostsRaw = normalizeQuotedValue(execGsettings('org.gnome.system.proxy', 'ignore-hosts'))
    const ignoreHosts = ignoreHostsRaw
      ? ignoreHostsRaw.replace(/^\[|\]$/g, '').split(',').map((item) => normalizeQuotedValue(item)).filter(Boolean)
      : []

    const env = {}
    if (httpHost && httpPort) {
      const proxy = buildProxyUrl({ scheme: 'http', host: httpHost, port: httpPort })
      env.http_proxy = proxy
      env.HTTP_PROXY = proxy
    }
    if (httpsHost && httpsPort) {
      const proxy = buildProxyUrl({ scheme: 'http', host: httpsHost, port: httpsPort })
      env.https_proxy = proxy
      env.HTTPS_PROXY = proxy
    } else if (env.http_proxy) {
      env.https_proxy = env.http_proxy
      env.HTTPS_PROXY = env.HTTP_PROXY
    }
    if (socksHost && socksPort) {
      const proxy = buildProxyUrl({ scheme: 'socks5', host: socksHost, port: socksPort })
      env.all_proxy = proxy
      env.ALL_PROXY = proxy
    }

    const noProxy = normalizeNoProxyList(ignoreHosts)
    if (noProxy) {
      env.no_proxy = noProxy
      env.NO_PROXY = noProxy
    }

    cachedSystemProxyEnv = env
    cachedSystemProxyEnvAt = now
    return { ...env }
  } catch (error) {
    cachedSystemProxyEnv = {}
    cachedSystemProxyEnvAt = now
    return {}
  }
}

function getSystemProxyEnv() {
  if (process.platform === 'darwin') return getMacSystemProxyEnv()
  if (process.platform === 'win32') return getWindowsSystemProxyEnv()
  if (process.platform === 'linux') return getLinuxSystemProxyEnv()
  return {}
}

function buildTerminalLaunchOptions({ shell, resolvedCwd, homeDir }) {
  const shellBase = path.basename(shell).replace(/\.exe$/i, '').toLowerCase()
  const requiredUnixPathEntries = [
    '/usr/local/bin',
    '/opt/homebrew/bin',
    '/usr/local/sbin',
    '/opt/homebrew/sbin',
    '/usr/bin',
    '/bin',
    '/usr/sbin',
    '/sbin'
  ]
  const env = {
    ...process.env,
    PWD: resolvedCwd,
    OLDPWD: homeDir,
    TERM: 'xterm-256color',
    COLORTERM: 'truecolor',
    LANG: process.env.LANG || 'en_US.UTF-8',
    TERM_PROGRAM: 'gitmanager'
  }

  if (process.platform !== 'win32') {
    env.PATH = ensurePathEntries(env.PATH, requiredUnixPathEntries)
  }

  const systemProxyEnv = getSystemProxyEnv()
  Object.assign(env, systemProxyEnv)

  if (process.platform === 'win32') {
    return { shellArgs: [], env, shellBase }
  }

  if (shellBase === 'zsh') {
    const { zshDir } = ensureTerminalBootstrapFiles()
    env.GIT_MANAGER_INITIAL_CWD = resolvedCwd
    env.GIT_MANAGER_REAL_ZDOTDIR = process.env.ZDOTDIR || homeDir
    env.ZDOTDIR = zshDir
    return { shellArgs: ['-il'], env, shellBase }
  }

  if (shellBase === 'bash') {
    const { bashRcPath } = ensureTerminalBootstrapFiles()
    env.GIT_MANAGER_INITIAL_CWD = resolvedCwd
    env.GIT_MANAGER_REAL_BASHRC = path.join(homeDir, '.bashrc')
    return { shellArgs: ['--rcfile', bashRcPath, '-i'], env, shellBase }
  }

  if (shellBase === 'fish') {
    env.GIT_MANAGER_INITIAL_CWD = resolvedCwd
    return { shellArgs: ['-i', '-C', `cd -- ${quoteShellArg(resolvedCwd)}`], env, shellBase }
  }

  return { shellArgs: [], env, shellBase }
}

// ============ 性能优化：git fetch 去重 ============
// 同一仓库短时间内只执行一次 git fetch，避免重复网络请求
const _fetchLocks = new Map() // key: repoPath, value: Promise
const _fetchTimestamps = new Map() // key: repoPath, value: timestamp
const FETCH_DEDUP_INTERVAL = 30 * 1000 // 30秒内不重复 fetch
const FETCH_CACHE_CLEANUP_INTERVAL = 5 * 60 * 1000 // 5 分钟清理一次过期条目

// 定期清理过期的 fetch 缓存条目，防止内存泄漏
setInterval(() => {
  const now = Date.now()
  for (const [key, timestamp] of _fetchTimestamps) {
    if (now - timestamp > FETCH_CACHE_CLEANUP_INTERVAL) {
      _fetchTimestamps.delete(key)
      _fetchLocks.delete(key)
    }
  }
}, FETCH_CACHE_CLEANUP_INTERVAL)

// ============ 性能优化：git status 短期缓存 ============
// 同一仓库 2 秒内复用上次 status 结果，避免同一刷新周期内重复调用
const _statusCache = new Map() // key: repoPath, value: { result, timestamp }
const STATUS_CACHE_TTL = 2000 // 2 秒

async function cachedGitStatus(repoPath) {
  const cached = _statusCache.get(repoPath)
  if (cached && Date.now() - cached.timestamp < STATUS_CACHE_TTL) {
    return cached.result
  }
  const result = await executeGitCommand(['git', 'status', '--porcelain'], repoPath)
  _statusCache.set(repoPath, { result, timestamp: Date.now() })
  return result
}

async function deduplicatedFetch(repoPath) {
  const now = Date.now()
  const lastFetch = _fetchTimestamps.get(repoPath) || 0

  // 如果 30 秒内已经 fetch 过，直接跳过
  if (now - lastFetch < FETCH_DEDUP_INTERVAL) {
    return { success: true, stdout: '', stderr: '', skipped: true }
  }

  // 如果有正在进行的 fetch，复用同一个 Promise
  if (_fetchLocks.has(repoPath)) {
    return _fetchLocks.get(repoPath)
  }

  const fetchPromise = executeGitCommand(['git', 'fetch', 'origin', '--quiet'], repoPath)
    .then(result => {
      _fetchTimestamps.set(repoPath, Date.now())
      _fetchLocks.delete(repoPath)
      return result
    })
    .catch(err => {
      _fetchLocks.delete(repoPath)
      return { success: false, error: err.message, stdout: '', stderr: '' }
    })

  _fetchLocks.set(repoPath, fetchPromise)
  return fetchPromise
}

// ============ 性能优化：带并发限制的批量执行 ============
async function promiseAllWithLimit(tasks, limit = 5) {
  const results = []
  let index = 0

  async function runNext() {
    const i = index++
    if (i >= tasks.length) return
    results[i] = await tasks[i]()
    await runNext()
  }

  const workers = Array.from({ length: Math.min(limit, tasks.length) }, () => runNext())
  await Promise.all(workers)
  return results
}

// ============ 工具函数：判断是否是 Git 写入命令 ============
function isGitWriteCommand(command) {
  if (!command) return false
  return (
    command.includes('git add') || command.includes('git commit') ||
    command.includes('git push') || command.includes('git pull') ||
    command.includes('git merge') || command.includes('git rebase') ||
    command.includes('git checkout') || command.includes('git reset') ||
    command.includes('git stash') || command.includes('git cherry-pick')
  )
}

// ============ 性能优化：GitLab projectId 缓存 ============
const _projectIdCache = new Map() // key: "url|projectPath", value: { id, timestamp }
const PROJECT_ID_CACHE_TTL = 10 * 60 * 1000 // 10 分钟过期

async function getGitlabProjectId(cleanUrl, token, projectPath) {
  const cacheKey = `${cleanUrl}|${projectPath}`
  const cached = _projectIdCache.get(cacheKey)
  if (cached && Date.now() - cached.timestamp < PROJECT_ID_CACHE_TTL) {
    return { success: true, projectId: cached.id }
  }

  const encodedProjectPath = projectPath.replace(/\//g, '%2F')
  const projectApiUrl = `${cleanUrl}/api/v4/projects/${encodedProjectPath}`

  const projectResponse = await fetch(projectApiUrl, {
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      'User-Agent': 'Git-Project-Viewer/1.0'
    }
  })

  if (!projectResponse.ok) {
    const errorText = await projectResponse.text()
    safeLog('❌ 获取项目信息失败:', projectResponse.status, errorText)
    return {
      success: false,
      message: `获取项目信息失败: ${projectResponse.status} ${projectResponse.statusText}`
    }
  }

  const project = await projectResponse.json()
  _projectIdCache.set(cacheKey, { id: project.id, timestamp: Date.now() })
  return { success: true, projectId: project.id }
}

// 创建 fetch 函数（带超时支持）
function fetch(url, options = {}) {
  return new Promise((resolve, reject) => {
    const urlObj = new URL(url)
    const isHttps = urlObj.protocol === 'https:'
    const client = isHttps ? https : http
    const timeoutMs = options.timeout || 30000 // 默认 30 秒超时

    const requestOptions = {
      hostname: urlObj.hostname,
      port: urlObj.port || (isHttps ? 443 : 80),
      path: urlObj.pathname + urlObj.search,
      method: options.method || 'GET',
      headers: options.headers || {},
      timeout: timeoutMs
    }

    const req = client.request(requestOptions, (res) => {
      let data = ''

      res.on('data', (chunk) => {
        data += chunk
      })

      res.on('end', () => {
        resolve({
          ok: res.statusCode >= 200 && res.statusCode < 300,
          status: res.statusCode,
          statusText: res.statusMessage || '',
          json: () => Promise.resolve(JSON.parse(data)),
          text: () => Promise.resolve(data)
        })
      })
    })

    req.on('timeout', () => {
      req.destroy()
      reject(new Error(`请求超时 (${timeoutMs / 1000}秒): ${url}`))
    })

    req.on('error', (error) => {
      reject(error)
    })

    if (options.body) {
      req.write(options.body)
    }

    req.end()
  })
}

// 安全的日志函数，避免 EPIPE 错误
const safeLog = (...args) => {
  try {
    if (process.env.NODE_ENV !== 'development') return
    if (process.stdout && !process.stdout.destroyed) {
      process.stdout.write(`${format(...args)}\n`)
    }
  } catch (e) {
    // 忽略 EPIPE 等输出错误
  }
}

const safeError = (...args) => {
  try {
    if (process.stderr && !process.stderr.destroyed) {
      process.stderr.write(`${format(...args)}\n`)
    }
  } catch (e) {
    // 忽略 EPIPE 等输出错误
  }
}

safeLog('🔧 自定义 fetch 函数已设置:', typeof fetch)

// 保持对窗口对象的全局引用
let mainWindow

// 初始化 electron-store
const store = new Store({
  defaults: {
    gitlabConfig: {},
    gitlabHistory: [],
    savedConfigs: [],
    browserFavorites: [],
    browserPasswords: []
  }
})

// 开发环境判断
const isDev = process.env.NODE_ENV === 'development'
let webTabManager = null
let sitePermissionManager = null
let sessionPartitionManager = null
let webTabLifecycleInterval = null
const floatingMenuResolvers = new Map()
const pendingPermissionCallbacks = new Map()
const pendingPermissionTimeouts = new Map()
const downloadHistory = new Map()
const configuredBrowserPartitions = new Set()
const SITE_PERMISSION_PARTITION = 'persist:main'
const SITE_PERMISSION_REQUEST_TIMEOUT_MS = 30_000
let nextPermissionRequestId = 0

function createPermissionRequestId() {
  nextPermissionRequestId += 1
  return `site-permission-${Date.now()}-${nextPermissionRequestId}`
}

function clearPendingPermissionTimeout(requestId) {
  const timeout = pendingPermissionTimeouts.get(requestId)
  if (timeout) {
    clearTimeout(timeout)
    pendingPermissionTimeouts.delete(requestId)
  }
}

function resolvePendingPermissionRequest({ requestId, decision = 'deny', remember = false, reason = '' } = {}) {
  if (!sitePermissionManager || !requestId) {
    return { success: false, error: 'invalid permission request resolution' }
  }

  const pendingRequest = sitePermissionManager.getPendingRequest(requestId)
  if (!pendingRequest) {
    if (reason) {
      safeLog(`[Permission] ignore missing request ${requestId}: ${reason}`)
    }
    return { success: false, error: 'request not found' }
  }

  if (remember && decision === 'allow') {
    sitePermissionManager.rememberDecision({
      partition: pendingRequest.partition,
      origin: pendingRequest.origin,
      permission: pendingRequest.permission,
      decision
    })
  }

  const resolvedRequest = sitePermissionManager.resolvePendingRequest({ requestId, decision })
  clearPendingPermissionTimeout(requestId)

  const callback = pendingPermissionCallbacks.get(requestId)
  pendingPermissionCallbacks.delete(requestId)

  if (callback) {
    try {
      callback(decision === 'allow')
    } catch (error) {
      safeError(`[Permission] callback failed for ${requestId}:`, error)
    }
  }

  return { success: Boolean(resolvedRequest), request: resolvedRequest }
}

function getPermissionOrigin(webContents, details = {}, requestingOrigin = '') {
  const rawOrigin = requestingOrigin
    || details.requestingOrigin
    || details.requestingUrl
    || details.securityOrigin
    || details.embeddingOrigin
    || webContents?.getURL?.()
    || ''

  return sitePermissionManager ? sitePermissionManager.normalizeOrigin(rawOrigin) : ''
}

function emitDownloadState(payload = {}) {
  if (!payload?.id) return
  if (!mainWindow || mainWindow.isDestroyed() || !mainWindow.webContents || mainWindow.webContents.isDestroyed()) {
    return
  }
  mainWindow.webContents.send('web-download-state-changed', payload)
}

function getTabPermissionContext({ tabId = '', origin = '', partition = '' } = {}) {
  const snapshot = tabId && webTabManager?.createRecoverySnapshot ? webTabManager.createRecoverySnapshot(tabId) : null
  const resolvedPartition = partition || snapshot?.partition || SITE_PERMISSION_PARTITION
  const rawOrigin = origin || snapshot?.url || ''
  const resolvedOrigin = sitePermissionManager?.normalizeOrigin(rawOrigin) || ''
  return {
    partition: resolvedPartition,
    origin: resolvedOrigin
  }
}

function configureBrowserSessionPartition(partition = SITE_PERMISSION_PARTITION) {
  if (!partition || configuredBrowserPartitions.has(partition)) {
    return
  }

  const webviewSession = session.fromPartition(partition)
  webviewSession.setProxy({ mode: 'system' }).catch((error) => {
    safeError(`[Proxy] failed to apply system proxy for partition ${partition}:`, error.message || error)
  })

  webviewSession.setPermissionRequestHandler((webContents, permission, callback, details = {}) => {
    const origin = getPermissionOrigin(webContents, details)
    if (!origin) {
      safeLog(`[Permission] deny ${permission}: missing origin`)
      callback(false)
      return
    }

    const rememberedDecision = sitePermissionManager.getRememberedDecision({
      partition,
      origin,
      permission
    })

    if (rememberedDecision === 'allow') {
      callback(true)
      return
    }

    if (rememberedDecision === 'deny') {
      callback(false)
      return
    }

    const defaultDecision = sitePermissionManager.getDefaultDecision(permission)
    if (defaultDecision !== 'ask') {
      safeLog(`[Permission] deny ${permission}: default policy`)
      callback(false)
      return
    }

    const tabId = webTabManager?.getTabIdByWebContentsId(webContents?.id) || ''
    if (!sitePermissionManager.shouldPromptRenderer({ tabId, defaultDecision })) {
      safeLog(`[Permission] deny ${permission}: unable to map tab for ${origin}`)
      callback(false)
      return
    }

    if (!webTabManager?.isActiveTab(tabId)) {
      safeLog(`[Permission] deny ${permission}: tab not active for ${origin}`)
      callback(false)
      return
    }

    if (!mainWindow || mainWindow.isDestroyed() || !mainWindow.webContents || mainWindow.webContents.isDestroyed()) {
      safeLog(`[Permission] deny ${permission}: renderer unavailable for ${origin}`)
      callback(false)
      return
    }

    const requestId = createPermissionRequestId()
    const pendingRequest = sitePermissionManager.createPendingRequest({
      requestId,
      partition,
      origin,
      permission,
      tabId,
      expiresAt: Date.now() + SITE_PERMISSION_REQUEST_TIMEOUT_MS
    })

    pendingPermissionCallbacks.set(requestId, callback)
    clearPendingPermissionTimeout(requestId)

    const timeout = setTimeout(() => {
      safeLog(`[Permission] deny ${permission}: renderer response timeout for ${origin}`)
      resolvePendingPermissionRequest({
        requestId,
        decision: 'deny',
        reason: 'timeout'
      })
    }, SITE_PERMISSION_REQUEST_TIMEOUT_MS)

    if (typeof timeout.unref === 'function') {
      timeout.unref()
    }

    pendingPermissionTimeouts.set(requestId, timeout)

    const promptPayload = sitePermissionManager.buildPromptPayload(pendingRequest)
    if (!promptPayload) {
      safeLog(`[Permission] deny ${permission}: invalid prompt payload for ${origin}`)
      resolvePendingPermissionRequest({
        requestId,
        decision: 'deny',
        reason: 'invalid-prompt-payload'
      })
      return
    }

    try {
      mainWindow.webContents.send('browser-permission-requested', promptPayload)
    } catch (error) {
      safeError(`[Permission] send prompt failed for ${requestId}:`, error)
      resolvePendingPermissionRequest({
        requestId,
        decision: 'deny',
        reason: 'renderer-send-failed'
      })
    }
  })

  webviewSession.setPermissionCheckHandler((webContents, permission, requestingOrigin, details = {}) => {
    const origin = getPermissionOrigin(webContents, details, requestingOrigin)
    if (!origin) {
      return false
    }

    const rememberedDecision = sitePermissionManager.getRememberedDecision({
      partition,
      origin,
      permission
    })

    return sitePermissionManager.getCheckDecision({
      permission,
      rememberedDecision
    })
  })

  webviewSession.on('will-download', (event, item) => {
    const downloadId = item.getGUID()
    const sendDownloadState = (state) => {
      const payload = {
        id: downloadId,
        state,
        fileName: item.getFilename(),
        totalBytes: item.getTotalBytes(),
        receivedBytes: item.getReceivedBytes(),
        url: item.getURL(),
        savePath: item.getSavePath() || '',
        partition
      }
      downloadHistory.set(downloadId, {
        ...(downloadHistory.get(downloadId) || {}),
        ...payload
      })
      emitDownloadState(payload)
    }

    sendDownloadState('started')
    item.on('updated', () => {
      sendDownloadState(item.isPaused() ? 'paused' : 'progress')
    })
    item.once('done', (e, state) => {
      const finalPath = item.getSavePath() || ''
      const current = downloadHistory.get(downloadId) || {}
      downloadHistory.set(downloadId, {
        ...current,
        savePath: finalPath
      })
      sendDownloadState(state === 'completed' ? 'completed' : 'interrupted')
    })
  })

  configuredBrowserPartitions.add(partition)
}

ipcMain.on('browser-floating-menu-action', (event, payload) => {
  const menuWindow = BrowserWindow.fromWebContents(event.sender)
  if (!menuWindow) return
  const resolve = floatingMenuResolvers.get(menuWindow.id)
  if (resolve) {
    const action = payload && typeof payload.action === 'string' ? payload.action : null
    floatingMenuResolvers.delete(menuWindow.id)
    resolve(action)
  }
  if (!menuWindow.isDestroyed()) {
    menuWindow.close()
  }
})

function createWindow() {
  // 防止重复创建窗口
  if (mainWindow) {
    safeLog('窗口已存在，聚焦到现有窗口')
    mainWindow.focus()
    return
  }
  
  safeLog('Creating window...')
  // 创建浏览器窗口
          mainWindow = new BrowserWindow({
            width: 1400,
            height: 900,
            minWidth: 1200,
            minHeight: 800,
            webPreferences: {
              nodeIntegration: false,
              contextIsolation: true,
              enableRemoteModule: false,
              preload: path.join(__dirname, 'preload.js'),
              webviewTag: true
            },
            titleBarStyle: 'hidden',
            trafficLightPosition: { x: 8, y: 8 },
            show: false
          })

  if (webTabManager) {
    webTabManager.attachWindow(mainWindow)
  }

  if (isDev) {
    // 开发模式：加载 Vite 开发服务器
    safeLog('Loading development server...')
    mainWindow.loadURL('http://localhost:5173')
    mainWindow.webContents.openDevTools()
  } else {
    // 生产模式：加载打包后的静态文件
    safeLog('Loading production build...')
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'))
  }

  // 当窗口准备好显示时显示
  mainWindow.once('ready-to-show', () => {
    safeLog('Window ready to show, showing window...')
    mainWindow.show()
  })


  // 监听页面加载失败
  mainWindow.webContents.on('did-fail-load', (event, errorCode, errorDescription, validatedURL) => {
    safeError('Page failed to load:', errorCode, errorDescription, validatedURL)
    // 在开发模式下，如果加载失败，尝试重新加载
    if (isDev) {
      safeLog('Retrying to load...')
      setTimeout(() => {
        mainWindow.loadURL('http://localhost:5173')
      }, 1000)
    }
  })

  // 开发模式下，监听 Vite HMR 更新，自动刷新窗口
  if (isDev) {
    // Vite 的 HMR 会自动处理大部分更新，但我们也可以监听文件变化
    // 注意：Vite 已经通过 websocket 处理 HMR，这里主要是备用方案
    mainWindow.webContents.on('dom-ready', () => {
      safeLog('DOM ready in development mode')
    })
  }

  // 当用户点击关闭按钮时，隐藏窗口到应用图标而不是关闭
  mainWindow.on('close', (event) => {
    if (!app.isQuiting) {
      event.preventDefault()
      mainWindow.hide()
      safeLog('📱 窗口已隐藏到应用图标')
    }
  })

  // 当窗口确实被关闭时（如强制退出）
  mainWindow.on('closed', () => {
    mainWindow = null
  })

  // 当窗口从后台切换到前台时，主动刷新待定文件检查
  mainWindow.on('focus', () => {
    safeLog('🔄 窗口获得焦点，主动刷新待定文件检查')
    // 发送消息到渲染进程，触发刷新
    if (mainWindow.webContents) {
      mainWindow.webContents.send('refresh-on-focus')
      safeLog('📡 [主进程] 已发送 refresh-on-focus 事件到前端')
    }
  })

  mainWindow.webContents.setWindowOpenHandler((details) => {
    return handleWindowOpen(details)
  })

  createMenu()
}

function createPopupWindow(url) {
  const newWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1200,
    minHeight: 800,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      enableRemoteModule: false,
      preload: path.join(__dirname, 'preload.js')
    },
    titleBarStyle: 'hidden',
    trafficLightPosition: { x: 8, y: 8 },
    show: false
  })

  newWindow.loadURL(url)
  newWindow.once('ready-to-show', () => {
    newWindow.show()
  })

  newWindow.on('close', (event) => {
    if (!app.isQuiting) {
      event.preventDefault()
      newWindow.hide()
      safeLog('📱 新窗口已隐藏到应用图标')
    }
  })
}

function handleWindowOpen({ url = '', disposition = '', frameName = '' } = {}) {
  const decision = decideWindowOpenAction({ url, disposition, frameName })
  safeLog('🔗 [主进程] 窗口打开策略:', { url, disposition, frameName, decision: decision.action })

  if (decision.action === 'tab') {
    if (mainWindow && mainWindow.webContents && !mainWindow.webContents.isDestroyed()) {
      mainWindow.webContents.send('open-url-in-new-tab', url)
    }
    return { action: 'deny' }
  }

  if (decision.action === 'window') {
    createPopupWindow(url)
    return { action: 'deny' }
  }

  if (url) {
    shell.openExternal(url).catch((error) => {
      safeError('openExternal failed:', error)
    })
  }
  return { action: 'deny' }
}

ipcMain.on('web-tab-password-captured', (event, payload = {}) => {
  try {
    if (!webTabManager || !mainWindow || mainWindow.isDestroyed()) {
      return
    }
    const senderId = event?.sender?.id
    const tabId = webTabManager.getTabIdByWebContentsId(senderId)
    if (!tabId) {
      return
    }
    mainWindow.webContents.send('web-tab-password-captured', {
      tabId,
      username: payload.username || '',
      password: payload.password || '',
      domain: payload.domain || '',
      url: payload.url || '',
      capturedAt: payload.capturedAt || Date.now()
    })
  } catch (error) {
    safeError('[PasswordCapture] forward failed:', error)
  }
})

ipcMain.handle('web-tab-create', async (event, { tabId, url, isPrivate = false, partition = '' } = {}) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    const resolvedPartition = partition
      || sessionPartitionManager?.getPartition({ isPrivate, tabId })
      || SITE_PERMISSION_PARTITION
    configureBrowserSessionPartition(resolvedPartition)
    webTabManager.createWebTab(tabId, url || 'about:blank', { partition: resolvedPartition })
    return { success: true, partition: resolvedPartition }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-destroy', async (event, { tabId }) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    const partition = webTabManager.getTabPartition(tabId)
    const success = webTabManager.destroyWebTab(tabId)
    if (success && sessionPartitionManager?.isPrivatePartition(partition)) {
      try {
        const targetSession = session.fromPartition(partition)
        await targetSession.clearStorageData()
      } catch (error) {
        safeError(`[Session] clear private partition failed: ${partition}`, error)
      }
    }
    return { success }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-activate', async (event, { tabId, bounds }) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return { success: webTabManager.activateWebTab(tabId, bounds || null) }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-navigate', async (event, { tabId, url }) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return { success: webTabManager.navigateWebTab(tabId, url) }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-hide-all', async () => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return { success: webTabManager.hideAllWebTabs() }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-set-bounds', async (event, { bounds }) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return { success: webTabManager.setActiveBounds(bounds || null) }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-reload', async (event, { tabId }) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return { success: webTabManager.reloadWebTab(tabId) }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-go-back', async (event, { tabId }) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return { success: webTabManager.goBack(tabId) }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-go-forward', async (event, { tabId }) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return { success: webTabManager.goForward(tabId) }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-evaluate', async (event, { tabId, script } = {}) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return await webTabManager.evaluateWebTab(tabId, script || '')
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('web-tab-restore', async (event, { tabId, url } = {}) => {
  try {
    if (!webTabManager) throw new Error('webTabManager not initialized')
    return webTabManager.restoreWebTab(tabId, url || '')
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('browser-open-download-folder', async (event, { id } = {}) => {
  const record = downloadHistory.get(id)
  if (!record?.savePath) {
    return { success: false, error: 'download save path not found' }
  }
  try {
    shell.showItemInFolder(record.savePath)
    return { success: true }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('browser-retry-download', async (event, { id } = {}) => {
  const record = downloadHistory.get(id)
  if (!record?.url) {
    return { success: false, error: 'download url not found' }
  }
  try {
    const webviewSession = session.fromPartition(record.partition || SITE_PERMISSION_PARTITION)
    webviewSession.downloadURL(record.url)
    downloadHistory.set(id, {
      ...record,
      retryCount: (record.retryCount || 0) + 1
    })
    return { success: true }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('browser-clear-download-history', async () => {
  downloadHistory.clear()
  return { success: true }
})

ipcMain.handle('browser-get-site-permissions', async (event, payload = {}) => {
  try {
    if (!sitePermissionManager) throw new Error('sitePermissionManager not initialized')
    const { partition, origin } = getTabPermissionContext({
      tabId: payload.tabId || '',
      origin: payload.origin || '',
      partition: payload.partition || ''
    })
    return {
      success: true,
      origin,
      partition,
      permissions: sitePermissionManager.listPermissionsForOrigin({ partition, origin })
    }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('browser-reset-site-permission', async (event, payload = {}) => {
  try {
    if (!sitePermissionManager) throw new Error('sitePermissionManager not initialized')
    const { partition, origin } = getTabPermissionContext({
      tabId: payload.tabId || '',
      origin: payload.origin || '',
      partition: payload.partition || ''
    })
    const success = sitePermissionManager.resetPermission({
      partition,
      origin,
      permission: payload.permission || ''
    })
    return { success, origin, partition }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('browser-reset-all-site-permissions', async (event, payload = {}) => {
  try {
    if (!sitePermissionManager) throw new Error('sitePermissionManager not initialized')
    const { partition, origin } = getTabPermissionContext({
      tabId: payload.tabId || '',
      origin: payload.origin || '',
      partition: payload.partition || ''
    })
    const success = sitePermissionManager.resetAllPermissionsForOrigin({
      partition,
      origin
    })
    return { success, origin, partition }
  } catch (error) {
    return { success: false, error: error.message }
  }
})

ipcMain.handle('browser-permission-respond', async (event, payload = {}) => {
  try {
    if (!mainWindow || mainWindow.isDestroyed() || !mainWindow.webContents || event.sender.id !== mainWindow.webContents.id) {
      return { success: false, error: 'invalid permission response sender' }
    }

    const requestId = typeof payload.requestId === 'string' ? payload.requestId : ''
    const decision = payload.decision === 'allow' ? 'allow' : 'deny'
    const remember = Boolean(payload.remember)
    return resolvePendingPermissionRequest({
      requestId,
      decision,
      remember,
      reason: 'renderer-response'
    })
  } catch (error) {
    safeError('[Permission] browser-permission-respond failed:', error)
    return { success: false, error: error.message }
  }
})

ipcMain.handle('browser-show-native-menu', async (event) => {
  try {
    const targetWindow = BrowserWindow.fromWebContents(event.sender)
    if (!targetWindow || targetWindow.isDestroyed()) return null

    let selectedAction = null
    const menu = Menu.buildFromTemplate([
      { label: '远端仓库', click: () => { selectedAction = 'remote-repo' } },
      { label: '仓库管理', click: () => { selectedAction = 'saved-projects' } },
      { label: '收藏管理', click: () => { selectedAction = 'favorites-manager' } },
      { label: '历史记录', click: () => { selectedAction = 'browsing-history' } },
      { label: '密码管理', click: () => { selectedAction = 'password-manager' } },
      { label: '下载管理', click: () => { selectedAction = 'download-panel' } },
      { type: 'separator' },
      { label: '备份管理', click: () => { selectedAction = 'backup-manager' } }
    ])

    return await new Promise((resolve) => {
      menu.popup({
        window: targetWindow,
        callback: () => resolve(selectedAction)
      })
    })
  } catch (error) {
    safeError('❌ 打开原生浏览器菜单失败:', error.message)
    return null
  }
})

ipcMain.handle('browser-show-floating-menu', async (event, { x, y } = {}) => {
  try {
    const targetWindow = BrowserWindow.fromWebContents(event.sender)
    if (!targetWindow || targetWindow.isDestroyed()) return null

    const menuWidth = 168
    const menuHeight = 320
    const display = screen.getDisplayNearestPoint({ x: Math.round(x || 0), y: Math.round(y || 0) })
    const workArea = display.workArea

    const targetX = Math.min(
      Math.max(workArea.x, Math.round((x || (workArea.x + menuWidth)) - menuWidth)),
      workArea.x + workArea.width - menuWidth
    )
    const targetY = Math.min(
      Math.max(workArea.y, Math.round(y || workArea.y)),
      workArea.y + workArea.height - menuHeight
    )

    const menuWindow = new BrowserWindow({
      width: menuWidth,
      height: menuHeight,
      x: targetX,
      y: targetY,
      frame: false,
      show: false,
      transparent: true,
      backgroundColor: '#00000000',
      resizable: false,
      movable: false,
      minimizable: false,
      maximizable: false,
      fullscreenable: false,
      skipTaskbar: true,
      alwaysOnTop: true,
      parent: targetWindow,
      webPreferences: {
        nodeIntegration: true,
        contextIsolation: false,
        sandbox: false
      }
    })

    const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  html, body {
    width: 100%;
    margin: 0;
    padding: 0;
    background: transparent;
    overflow: hidden;
  }
  .menu {
    width: 100%;
    box-sizing: border-box;
    background: #2d2d2d;
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 8px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.3);
    color: rgba(255,255,255,0.9);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    user-select: none;
    padding: 4px 0;
    display: flex;
    flex-direction: column;
  }
  .item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 10px 16px;
    font-size: 14px;
    cursor: pointer;
  }
  .item:hover { background: rgba(255,255,255,0.1); }
  .icon {
    width: 16px;
    text-align: center;
    opacity: 0.9;
  }
  .divider {
    height: 1px;
    margin: 4px 0;
    background: rgba(255,255,255,0.1);
  }
</style>
</head>
<body>
  <div class="menu">
    <div class="item" data-action="remote-repo"><span class="icon">☁</span><span>远端仓库</span></div>
    <div class="item" data-action="saved-projects"><span class="icon">▦</span><span>仓库管理</span></div>
    <div class="item" data-action="favorites-manager"><span class="icon">☆</span><span>收藏管理</span></div>
    <div class="item" data-action="browsing-history"><span class="icon">◷</span><span>历史记录</span></div>
    <div class="item" data-action="password-manager"><span class="icon">⌘</span><span>密码管理</span></div>
    <div class="item" data-action="download-panel"><span class="icon">⇩</span><span>下载管理</span></div>
    <div class="divider"></div>
    <div class="item" data-action="backup-manager"><span class="icon">⬢</span><span>备份管理</span></div>
  </div>
  <script>
    const { ipcRenderer } = require('electron');
    const send = (action) => ipcRenderer.send('browser-floating-menu-action', { action });
    document.querySelectorAll('.item').forEach(el => {
      el.addEventListener('click', () => send(el.dataset.action || null));
    });
    window.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') send(null);
    });
    window.addEventListener('blur', () => send(null));
  </script>
</body>
</html>`

    await menuWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`)

    const measuredHeight = await menuWindow.webContents.executeJavaScript(`
      (() => {
        const menu = document.querySelector('.menu')
        if (!menu) return ${menuHeight}
        return Math.ceil(menu.getBoundingClientRect().height)
      })()
    `)

    const finalHeight = Math.max(1, Number(measuredHeight) || menuHeight)
    const finalY = Math.min(
      Math.max(workArea.y, Math.round(y || workArea.y)),
      workArea.y + workArea.height - finalHeight
    )

    menuWindow.setBounds({
      x: targetX,
      y: finalY,
      width: menuWidth,
      height: finalHeight
    })

    if (!menuWindow.isDestroyed()) {
      menuWindow.show()
      menuWindow.focus()
    }

    return await new Promise((resolve) => {
      floatingMenuResolvers.set(menuWindow.id, resolve)
      menuWindow.on('closed', () => {
        const resolver = floatingMenuResolvers.get(menuWindow.id)
        if (resolver) {
          floatingMenuResolvers.delete(menuWindow.id)
          resolver(null)
        }
      })
    })
  } catch (error) {
    safeError('❌ 打开浮层菜单失败:', error.message)
    return null
  }
})

// Git 操作函数
async function executeGitCommand(command, cwd) {
  try {
    if (Array.isArray(command)) {
      const [cmd, ...args] = command
      return await executeCommandArgs(cmd, args, cwd)
    }
    const { stdout, stderr } = await execAsync(command, { cwd })
    return { success: true, stdout: stdout || '', stderr: stderr || '' }
  } catch (error) {
    return { 
      success: false, 
      error: error.message, 
      stdout: error.stdout || '', 
      stderr: error.stderr || '' 
    }
  }
}

// 检查并修正Git仓库的remote地址
async function checkAndFixRemoteUrl(repoPath, correctUrl, projectName) {
  if (!correctUrl || !correctUrl.includes('git@')) {
    return { success: true, message: '', fixed: false }
  }
  
  try {
    safeLog(`🔍 检查项目 ${projectName} 的remote地址`)
    
    // 获取当前remote地址
    const remoteResult = await executeGitCommand(['git', 'remote', 'get-url', 'origin'], repoPath)
    
    if (remoteResult.success && remoteResult.stdout) {
      const currentUrl = remoteResult.stdout.trim()
      safeLog(`📋 当前remote地址: ${currentUrl}`)
      safeLog(`🎯 正确的remote地址: ${correctUrl}`)
      
      if (currentUrl === correctUrl) {
        safeLog(`✅ 远程地址正确: ${projectName}`)
        return { success: true, message: '', fixed: false }
      } else {
        safeLog(`🔧 需要修正remote地址: ${projectName}`)
        
        // 修正remote地址
        const fixResult = await executeGitCommand(['git', 'remote', 'set-url', 'origin', correctUrl], repoPath)
        
        if (fixResult.success) {
          safeLog(`✅ remote地址修正成功: ${projectName}`)
          return { success: true, message: `已修正remote地址: ${correctUrl}`, fixed: true }
        } else {
          safeLog(`❌ remote地址修正失败: ${projectName}`)
          return { success: false, message: `修正remote地址失败: ${fixResult.stderr}`, fixed: false }
        }
      }
    } else {
      // 如果没有origin remote，创建它
      safeLog(`🔧 创建origin remote: ${projectName}`)
      const addRemoteResult = await executeGitCommand(['git', 'remote', 'add', 'origin', correctUrl], repoPath)
      
      if (addRemoteResult.success) {
        safeLog(`✅ origin remote创建成功: ${projectName}`)
        return { success: true, message: `已创建origin remote: ${correctUrl}`, fixed: true }
      } else {
        safeLog(`❌ origin remote创建失败: ${projectName}`)
        return { success: false, message: `创建origin remote失败: ${addRemoteResult.stderr}`, fixed: false }
      }
    }
  } catch (error) {
    safeError(`❌ 检查remote地址失败 ${projectName}:`, error.message)
    return { success: false, message: `检查remote地址失败: ${error.message}`, fixed: false }
  }
}

// 带实时输出的Git命令执行
async function executeGitCommandWithOutput(command, cwd, processCallback = null) {
  return new Promise((resolve) => {
    const { spawn } = require('child_process')

    safeLog(`📡 执行命令: ${command.join(' ')} @ ${cwd}`)

    const windows = BrowserWindow.getAllWindows()
    const mainWindow = windows.find(w => w.webContents.getURL().includes('localhost:5173')) || windows[0]
    const sendRealtimeOutput = (output, type) => {
      if (processCallback) {
        processCallback(output, type)
        return
      }
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('git-output-update', {
          projectName: 'unknown',
          output,
          type
        })
      }
    }

    const child = spawn(command[0], command.slice(1), {
      cwd: cwd,
      stdio: ['ignore', 'pipe', 'pipe']
    })

    let stdoutData = ''
    let stderrData = ''
    let settled = false
    const timeoutMs = 10 * 60 * 1000
    const timeout = setTimeout(() => {
      if (settled) return
      settled = true
      safeError(`⏰ 命令执行超时 (${timeoutMs / 1000}s): ${command.join(' ')}`)
      try { child.kill('SIGTERM') } catch (e) { /* ignore */ }
      setTimeout(() => {
        try { child.kill('SIGKILL') } catch (e) { /* ignore */ }
      }, 5000)
      resolve({
        success: false,
        code: -1,
        stdout: stdoutData,
        stderr: stderrData || `命令执行超时 (${timeoutMs / 1000}秒)`,
        timeout: true
      })
    }, timeoutMs)

    child.stdout.on('data', (data) => {
      const output = data.toString()
      stdoutData += output
      if (output) {
        sendRealtimeOutput(output, 'stdout')
      }
    })

    child.stderr.on('data', (data) => {
      const output = data.toString()
      stderrData += output
      if (output) {
        sendRealtimeOutput(output, 'stderr')
      }
    })

    child.on('close', (code) => {
      if (settled) return
      settled = true
      clearTimeout(timeout)
      safeLog(`📋 命令执行完成，退出码: ${code}`)
      safeLog(`📋 命令结果: ${code === 0 ? '成功' : '失败'} (${command[0]})`)
      resolve({
        success: code === 0,
        code: code,
        stdout: stdoutData,
        stderr: stderrData
      })
    })

    child.on('error', (error) => {
      if (settled) return
      settled = true
      clearTimeout(timeout)
      safeError(`❌ 命令执行错误: ${error.message}`)
      resolve({
        success: false,
        error: error.message,
        code: -1,
        stdout: stdoutData,
        stderr: stderrData
      })
    })
  })
}

function createMenu() {
  const template = [
    {
      label: '应用',
      submenu: [
        { label: '关于', role: 'about' },
        { type: 'separator' },
        { label: '退出' }
      ]
    },
    {
      label: '编辑',
      submenu: [
        { label: '撤销', accelerator: 'Command+Z', role: 'undo' },
        { label: '重做', accelerator: 'Shift+Command+Z', role: 'redo' },
        { type: 'separator' },
        { label: '剪切', accelerator: 'Command+X', role: 'cut' },
        { label: '复制', accelerator: 'Command+C', role: 'copy' },
        { label: '粘贴', accelerator: 'Command+V', role: 'paste' },
        { label: '全选', accelerator: 'Command+A', role: 'selectAll' }
      ]
    },
    {
      label: '视图',
      submenu: [
        { 
          label: '重新加载当前标签页', 
          accelerator: 'Command+R', 
          click: () => {
            safeLog('⌨️ Command+R 快捷键被触发')
            // 向渲染进程发送刷新当前标签页的消息
            if (mainWindow && mainWindow.webContents) {
              safeLog('📡 发送 refresh-current-tab 消息到渲染进程')
              mainWindow.webContents.send('refresh-current-tab')
            } else {
              safeLog('❌ mainWindow 或 webContents 不可用')
            }
          }
        },
        { label: '强制重新加载', accelerator: 'Command+Shift+R', role: 'forceReload' },
        { label: '切换开发者工具', accelerator: 'F12', role: 'toggleDevTools' },
        { 
          label: '打开 Webview 开发者工具', 
          accelerator: 'Command+Option+I',
          click: () => {
            if (mainWindow && mainWindow.webContents) {
              mainWindow.webContents.send('open-webview-devtools')
            }
          }
        },
        { type: 'separator' },
        { label: '实际大小', accelerator: 'Command+0', role: 'resetZoom' },
        { label: '放大', accelerator: 'Command+Plus', role: 'zoomIn' },
        { label: '缩小', accelerator: 'Command+-', role: 'zoomOut' },
        { type: 'separator' },
        { label: '切换全屏', accelerator: 'Ctrl+Command+F', role: 'togglefullscreen' }
      ]
    },
    {
      label: '收藏',
      submenu: [
        {
          label: '导出收藏',
          click: () => {
            if (mainWindow && mainWindow.webContents) {
              mainWindow.webContents.send('export-favorites')
            }
          }
        },
        {
          label: '导入收藏',
          click: () => {
            if (mainWindow && mainWindow.webContents) {
              mainWindow.webContents.send('import-favorites')
            }
          }
        }
      ]
    },
    {
      label: '窗口',
      submenu: [
        { label: '最小化', accelerator: 'Command+M', role: 'minimize' },
        { label: '关闭', accelerator: 'Command+W', role: 'close' }
      ]
    },
    {
      label: '帮助',
      submenu: [
        {
          label: '了解更多',
          click: () => {
            shell.openExternal('https://github.com/TerraRoot3/OpenGit')
          }
        }
      ]
    }
  ]

  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
}

// 当 Electron 完成初始化并准备创建浏览器窗口时调用此方法
safeLog('Electron app starting...')

registerWindowUiHandlers({
  ipcMain,
  safeLog,
  safeError
})

// Store 已在文件顶部声明

// 刷新相关处理器
registerRefreshHandlers({
  ipcMain,
  getMainWindow: () => mainWindow,
  safeLog,
  safeError
})

// 配置存储相关处理器
registerConfigHandlers({
  ipcMain,
  store,
  safeLog,
  safeError
})

// 文件系统操作处理器
registerFilesystemHandlers({
  ipcMain,
  getMainWindow: () => mainWindow,
  executeGitCommand,
  safeLog,
  safeError
})

registerAiSessionHandlers({
  ipcMain,
  safeError,
  summaryCacheFilePath: path.join(app.getPath('userData'), 'cache', 'ai-session-summary-cache.json')
})


// 检查并处理 Git 锁文件
async function checkAndRemoveGitLock(cwd) {
  try {
    const lockPath = path.join(cwd, '.git', 'index.lock')
    
    // 检查锁文件是否存在
    if (!fs.existsSync(lockPath)) {
      return { removed: false, reason: 'no_lock' }
    }
    
    safeLog('⚠️ 检测到 Git 锁文件:', lockPath)
    
    // 检查锁文件的修改时间（如果超过1分钟，认为是僵尸锁文件）
    const stats = fs.statSync(lockPath)
    const ageSeconds = (Date.now() - stats.mtime.getTime()) / 1000
    
    // 锁文件较新时严格保守，不自动删除
    if (ageSeconds < 120) {
      return { removed: false, reason: 'lock_recent', age: ageSeconds }
    }

    // 锁文件较旧（>=120s），仅在确认没有持有进程时删除
    try {
      const { execSync } = require('child_process')

      const lsofResult = execSync(`lsof "${lockPath}" 2>/dev/null || true`, { encoding: 'utf-8', timeout: 1200 })
      if (lsofResult.trim()) {
        safeLog('⏳ 检测到进程正在持有 lock 文件，跳过删除')
        return { removed: false, reason: 'file_in_use', age: ageSeconds }
      }

      safeLog(`🔓 未检测到持有进程，删除陈旧 lock 文件 (${ageSeconds.toFixed(1)}s)`)
      fs.unlinkSync(lockPath)
      return { removed: true, reason: 'stale_lock_no_owner', age: ageSeconds }
    } catch (error) {
      // lsof 不可用或检查失败时，严格保守：不删除
      safeLog('⚠️ 无法确认 lock 文件持有者，保守跳过删除:', error.message)
      return { removed: false, reason: 'cannot_verify_owner', age: ageSeconds }
    }
  } catch (error) {
    safeError('❌ 处理 Git 锁文件失败:', error.message)
    return { removed: false, reason: 'error', error: error.message }
  }
}

registerCommandHandlers({
  ipcMain,
  isGitWriteCommand,
  checkAndRemoveGitLock,
  safeLog,
  safeError
})

registerNavigationHandlers({
  ipcMain,
  shell,
  getMainWindow: () => mainWindow,
  safeLog,
  safeError
})

registerBrowserDataHandlers({
  ipcMain,
  getMainWindow: () => mainWindow,
  store,
  safeLog,
  safeError
})

registerProjectHandlers({
  ipcMain,
  store,
  executeGitCommand,
  promiseAllWithLimit,
  notifyProjectsUpdated: (projectPath, projects) => {
    const windows = BrowserWindow.getAllWindows()
    windows.forEach(win => {
      if (win && !win.isDestroyed()) {
        win.webContents.send('projects-updated', { path: projectPath, projects })
      }
    })
  },
  safeLog,
  safeError
})

registerBranchHandlers({
  ipcMain,
  store,
  executeGitCommand,
  cachedGitStatus,
  deduplicatedFetch,
  getMainWindow: () => mainWindow,
  safeLog,
  safeError
})

// 监听所有 webContents 创建，拦截 webview 中的新窗口请求
app.on('web-contents-created', (event, contents) => {
  contents.setWindowOpenHandler((details) => handleWindowOpen(details))
  
  // 为 webview 设置导航处理
  contents.on('will-navigate', (event, url) => {
    safeLog('🔗 [主进程] webContents will-navigate:', url)
  })
})


app.whenReady().then(async () => {
  safeLog('Electron app ready, creating window...')
  await session.defaultSession.setProxy({ mode: 'system' }).catch((error) => {
    safeError('[Proxy] failed to apply system proxy for default session:', error.message || error)
  })
  webTabManager = new WebTabManager({
    safeLog,
    safeError,
    lifecycleOptions: {
      discardDelayMs: Number.POSITIVE_INFINITY
    },
    webTabPreloadPath: path.join(__dirname, 'web-tab-preload.js')
  })
  sitePermissionManager = createSitePermissionManager({ store })
  sessionPartitionManager = createSessionPartitionManager()

  webTabLifecycleInterval = setInterval(() => {
    if (!webTabManager) return
    const transitions = webTabManager.advanceLifecycle(Date.now())
    if (!Array.isArray(transitions) || transitions.length === 0) return

    for (const transition of transitions) {
      const [tabId, phase] = String(transition).split(':')
      if (!tabId || !phase) continue
      if (phase === 'discarded') {
        webTabManager.discardWebTab(tabId)
      }
    }
  }, 1000)

  if (typeof webTabLifecycleInterval.unref === 'function') {
    webTabLifecycleInterval.unref()
  }

  // 注册 local-resource:// 协议：安全地将 ~/.gitManager/ 下的文件提供给渲染进程
  // URL 格式：local-resource://相对路径  例：local-resource://screenshots/screenshot-123.png
  const gitManagerBase = path.resolve(os.homedir(), '.gitManager')
  session.defaultSession.protocol.handle('local-resource', (request) => {
    try {
      const url = new URL(request.url)
      // url.host + url.pathname 拼合出相对路径，例如 "screenshots/screenshot-123.png"
      const relPath = decodeURIComponent((url.host || '') + url.pathname)
      const fullPath = path.resolve(gitManagerBase, relPath)
      // 安全校验：只允许访问 ~/.gitManager/ 下的文件
      if (!fullPath.startsWith(gitManagerBase + path.sep) && fullPath !== gitManagerBase) {
        return new Response('Forbidden', { status: 403 })
      }
      return net.fetch(pathToFileURL(fullPath).toString())
    } catch (e) {
      return new Response('Internal Error', { status: 500 })
    }
  })

  configureBrowserSessionPartition(SITE_PERMISSION_PARTITION)
  
  // 设置存储路径（确保使用应用数据目录）
  const userDataPath = app.getPath('userData')
  safeLog(`📁 User data path: ${userDataPath}`)
  safeLog(`✅ Webview session configured with persist:main`)
  
  createWindow()

}).catch((error) => {
  safeError('Error in app.whenReady():', error)
})

// 添加应用退出标记
app.isQuiting = false

app.on('before-quit', async () => {
  app.isQuiting = true


  // 确保 webview session 的所有存储数据被刷新到磁盘
  try {
    const webviewSession = session.fromPartition('persist:main')
    
    // 刷新 cookies
    await webviewSession.cookies.flushStore()
    safeLog('✅ Session cookies flushed to disk')
    
    // 刷新存储缓存（包括 localStorage, IndexedDB 等）
    // Electron 会在 session 关闭时自动保存，但显式刷新更可靠
    if (webviewSession.flushStorageData) {
      webviewSession.flushStorageData()
      safeLog('✅ Storage data flushed to disk')
    }
    
    // 清理未使用的缓存（可选，保持磁盘空间）
    // await webviewSession.clearCache() // 不清理，保持缓存
    
    safeLog('✅ All session data saved')
  } catch (error) {
    safeError('❌ Failed to flush session data:', error)
  }
})

app.on('window-all-closed', () => {
  // 在macOS上，应用会继续运行，即使所有窗口都关闭了
  // 只有当用户明确退出应用时才真正退出
})

app.on('activate', () => {
  // 如果有隐藏的窗口，就显示它们
  if (mainWindow && !mainWindow.isVisible()) {
    mainWindow.show()
    safeLog('📱 恢复隐藏的主窗口')
  } else if (BrowserWindow.getAllWindows().length === 0) {
    // 如果没有窗口，创建新窗口
    createWindow()
  }
})

registerScmHandlers({
  ipcMain,
  BrowserWindow,
  fs,
  path,
  store,
  fetch,
  executeGitCommand,
  executeGitCommandWithOutput,
  checkAndFixRemoteUrl,
  getGitlabProjectId,
  safeLog,
  safeError
})

// ==================== PTY 终端 ====================
const { cleanup: cleanupTerminalSessions } = registerTerminalHandlers({
  ipcMain,
  BrowserWindow,
  app,
  pty,
  fs,
  path,
  fileURLToPath,
  buildTerminalLaunchOptions,
  safeLog,
  getMainWindow: () => mainWindow
})

app.on('will-quit', () => {
  if (webTabLifecycleInterval) {
    clearInterval(webTabLifecycleInterval)
    webTabLifecycleInterval = null
  }
  if (webTabManager) {
    webTabManager.cleanup()
  }
  cleanupTerminalSessions()
})

registerExtensionHandlers({
  ipcMain,
  dialog,
  app,
  store,
  getMainWindow: () => mainWindow,
  safeLog,
  safeError
})
